version: "3.2"
services:
  develop:
    container_name: auth
    build:
      context: .
      target: development
      dockerfile: "Dockerfile"
    ports:
      - 80:9099
    volumes:
      - .:/var/www/html/
    restart: always
    working_dir: /var/www/html
    command: sh -c "npm install --force && npm run migration:up && npm run db:seed && npm run start:dev"
    # environment:
    #    DATABASE_HOST: core-auth-dev.db.cisholdingdigital.com
    #    DATABASE_PASSWORD: 94tiPyv05o6p
    #    DATABASE_PORT: 5432
    #    DATABASE_USERNAME: postgres
    #    DATABASE_NAME: coreauthdev
    env_file:
      - .env